package com.placementcompass.api.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * InterviewRound — an embedded document inside JobApplication.
 *
 * Design: @Document is intentionally NOT used here.
 * This class is embedded inside the "applications" MongoDB collection as a
 * nested array element, not stored in its own collection.
 *
 * MongoDB document shape:
 * {
 *   "_id": "app123",
 *   "companyName": "Google",
 *   "rounds": [
 *     {
 *       "roundId": "uuid-generated",
 *       "roundNumber": 1,
 *       "type": "TECHNICAL",
 *       "outcome": "PASSED",
 *       "scheduledAt": "2025-08-15T10:00",
 *       "durationMinutes": 60,
 *       "interviewer": "Priya Sharma",
 *       "notes": "Binary trees, DP, two pointers"
 *     }
 *   ]
 * }
 *
 * roundId generation:
 * Since this is embedded (not a @Document with @Id auto-generation),
 * the service manually generates a UUID for roundId on creation.
 * This allows the frontend to reference specific rounds for updates/deletes.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InterviewRound {

    /** Stable identifier for this round — UUID generated by the service on create */
    private String roundId;

    /** Order of this round (1 = first, 2 = second, etc.) */
    private int roundNumber;

    /** Format of this interview round */
    private InterviewRoundType type;

    /** Result after the round completes; defaults to PENDING */
    private InterviewRoundOutcome outcome;

    /** When the round is/was scheduled */
    private LocalDateTime scheduledAt;

    /** Estimated or actual duration in minutes */
    private Integer durationMinutes;

    /** Name/designation of the interviewer (if known) */
    private String interviewer;

    /** Platform: Zoom, Google Meet, In-person, HackerRank, etc. */
    private String platform;

    /** Prep notes, topics covered, feedback received */
    private String notes;
}
